FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["ServerSocket.csproj", "./"]


RUN dotnet restore "ServerSocket.csproj"

COPY . .

RUN dotnet publish "ServerSocket.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/runtime:10.0 AS final
WORKDIR /app

EXPOSE 11000
ENV LOG_DIR="/app/logs"

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "ServerSocket.dll"]